package com.example.belle.data.service;

import com.twilio.rest.verify.v2.service.Verification;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.example.belle.config.TwilioConfig;

@Service
public class TwilioService {

    @Autowired
    private TwilioConfig twilioConfig;

    public Verification sendOtp(String phoneNumber) {
        Verification verification = Verification.creator(
                        twilioConfig.getVerifyServiceSid(),
                        phoneNumber,
                        "sms")
                .create();

        System.out.println("OTP SID: " + verification.getSid());
        return verification;
    }

    public String generateOtp() {
        // Twilio sẽ tự động tạo OTP trong quá trình gửi
        return "OTP generated by Twilio service";
    }
}